"""
Insight-digest subscriptions (feature #219)

Lets a user opt in to a daily/weekly email summarising changes to a dashboard
or KPI card. Each delivery is generated by `redash.tasks.digest.send_digests`
on a schedule and includes:
  - The latest metric value
  - The delta vs the prior period
  - A sparkline PNG of recent history (embedded as data: URI)
  - The auto-narrative summary
  - An unsubscribe link (token-based, no auth required)
  - A link back to the source dashboard / query

The unsubscribe token is a SHA-256 of (subscription_id, user_id, secret) so it
can't be guessed and is invalidated by simply deleting the row.

Kept in a separate module so the main `redash/models/__init__.py` (~1500 lines)
doesn't keep growing. Imported at the bottom of that module so SQLAlchemy
metadata is registered against the same MetaData object.
"""
import datetime
import hashlib

from sqlalchemy.dialects.postgresql import JSONB

from redash import settings
from redash.models.base import Column, db, key_type, primary_key
from redash.models.mixins import BelongsToOrgMixin, TimestampMixin
from redash.models.organizations import Organization
from redash.models.users import User
from redash.utils import generate_token


FREQUENCY_DAILY = "daily"
FREQUENCY_WEEKLY = "weekly"
ALLOWED_FREQUENCIES = (FREQUENCY_DAILY, FREQUENCY_WEEKLY)

TARGET_DASHBOARD = "dashboard"
TARGET_QUERY = "query"  # interpreted as the KPI Card visualization on that query
ALLOWED_TARGETS = (TARGET_DASHBOARD, TARGET_QUERY)


class DigestSubscription(TimestampMixin, BelongsToOrgMixin, db.Model):
    """A user's standing subscription to a scheduled digest email."""

    id = primary_key("DigestSubscription")
    org_id = Column(key_type("Organization"), db.ForeignKey("organizations.id"))
    org = db.relationship(Organization)

    user_id = Column(key_type("User"), db.ForeignKey("users.id"))
    user = db.relationship(User)

    target_type = Column(db.String(32), nullable=False)  # "dashboard" | "query"
    target_id = Column(db.Integer, nullable=False)

    frequency = Column(db.String(16), nullable=False, default=FREQUENCY_DAILY)
    # Hour of day (0-23, UTC) at which the digest should be sent.
    delivery_hour = Column(db.Integer, nullable=False, default=8)

    last_sent_at = Column(db.DateTime(True), nullable=True)
    last_payload = Column(JSONB, nullable=True)

    # Token used to authenticate the unsubscribe link without a session.
    unsubscribe_token = Column(db.String(64), nullable=False)

    active = Column(db.Boolean, default=True, nullable=False)

    __tablename__ = "digest_subscriptions"
    __table_args__ = (
        db.UniqueConstraint(
            "user_id",
            "target_type",
            "target_id",
            "frequency",
            name="digest_subscriptions_unique",
        ),
    )

    # ---- factory ---------------------------------------------------------

    @classmethod
    def create(cls, user, target_type, target_id, frequency=FREQUENCY_DAILY, delivery_hour=8):
        if target_type not in ALLOWED_TARGETS:
            raise ValueError(f"Invalid target_type: {target_type}")
        if frequency not in ALLOWED_FREQUENCIES:
            raise ValueError(f"Invalid frequency: {frequency}")
        if not (0 <= int(delivery_hour) <= 23):
            raise ValueError(f"delivery_hour must be 0-23, got {delivery_hour}")

        sub = cls(
            org_id=user.org_id,
            user_id=user.id,
            target_type=target_type,
            target_id=int(target_id),
            frequency=frequency,
            delivery_hour=int(delivery_hour),
            unsubscribe_token=generate_token(40),
            active=True,
        )
        return sub

    # ---- queries ---------------------------------------------------------

    @classmethod
    def all_for_user(cls, user):
        return cls.query.filter(cls.user_id == user.id, cls.active.is_(True)).order_by(cls.id.asc())

    @classmethod
    def get_active_for_dispatch(cls, frequency, now=None):
        """Return active subscriptions whose hour-of-day matches `now` and
        whose last_sent_at is far enough in the past for the given frequency.
        """
        now = now or datetime.datetime.utcnow()
        q = cls.query.filter(cls.active.is_(True), cls.frequency == frequency, cls.delivery_hour == now.hour)
        if frequency == FREQUENCY_DAILY:
            min_age = datetime.timedelta(hours=23)
        elif frequency == FREQUENCY_WEEKLY:
            min_age = datetime.timedelta(days=6, hours=23)
        else:
            return q.filter(False)  # never matches
        cutoff = now - min_age
        return q.filter((cls.last_sent_at.is_(None)) | (cls.last_sent_at <= cutoff))

    # ---- unsubscribe -----------------------------------------------------

    def compute_unsubscribe_signature(self):
        """Deterministic per-row signature used inside the email link.

        Composed of (sub_id || user_id || stored_token || SECRET_KEY). The
        SECRET_KEY clause means signatures can be globally invalidated by
        rotating the secret; rotating just `unsubscribe_token` invalidates
        a single subscription.
        """
        secret = (settings.SECRET_KEY or "").encode("utf-8")
        material = f"{self.id}:{self.user_id}:{self.unsubscribe_token}".encode("utf-8")
        return hashlib.sha256(material + secret).hexdigest()

    def verify_unsubscribe_signature(self, candidate):
        return bool(candidate) and candidate == self.compute_unsubscribe_signature()

    # ---- serialisation ---------------------------------------------------

    def to_dict(self):
        return {
            "id": self.id,
            "user_id": self.user_id,
            "target_type": self.target_type,
            "target_id": self.target_id,
            "frequency": self.frequency,
            "delivery_hour": self.delivery_hour,
            "active": self.active,
            "last_sent_at": self.last_sent_at.isoformat() if self.last_sent_at else None,
        }
